# Default values for rustic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cronjob:
  schedule: "0 1 * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  restartPolicy: OnFailure

nameOverride: ""
fullnameOverride: ""

rustic:
  image:
    repository: ghcr.io/mueckinger/rustic
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  init: false
  resources:
    requests:
      memory: 50Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
