apiVersion: v1
entries:
  rustic:
  - apiVersion: v2
    appVersion: 0.6.1
    created: "2024-01-12T18:11:53.714144944+01:00"
    description: fast, encrypted and deduplicated backups
    digest: 3c8a0219a14bf8cf25d3cea57bee4a326144f0e8138656a58b692fb7ece2e533
    name: rustic
    type: application
    urls:
    - https://github.com/rustic-rs/rustic-helm/releases/download/0.1.1-alpha/charts/rustic-0.1.1-alpha.tgz
    version: 0.1.1-alpha
  - apiVersion: v2
    appVersion: 0.6.1
    created: "2024-01-06T14:01:32.369624462+01:00"
    description: fast, encrypted and deduplicated backups
    digest: 8e783811d5bcd0adfd3778af753e9839aaedf2a3dd529124f3285a25f896cf95
    name: rustic
    type: application
    urls:
    - https://github.com/rustic-rs/rustic-helm/releases/download/0.1.0-alpha/rustic-0.1.0-alpha.tgz
    version: 0.1.0-alpha
generated: "2024-01-12T18:11:53.712973339+01:00"
