apiVersion: v1
entries:
  rustic:
  - apiVersion: v2
    appVersion: 0.6.1
    created: "2024-01-06T14:01:32.369624462+01:00"
    description: fast, encrypted and deduplicated backups
    digest: 8e783811d5bcd0adfd3778af753e9839aaedf2a3dd529124f3285a25f896cf95
    name: rustic
    type: application
    urls:
    - https://rustic-rs.github.io/rustic-helm/charts/rustic-0.1.0-alpha.tgz
    version: 0.1.0-alpha
generated: "2024-01-06T14:01:32.368707107+01:00"
