apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "rustic.fullname" . }}
  labels:
    {{- include "rustic.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "rustic.labels" . | nindent 12 }}
        spec:
          automountServiceAccountToken: false
          hostname: {{ .Values.hostname }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.rustic.image.repository }}:{{ .Values.rustic.image.tag  | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.rustic.image.pullPolicy }}
              args:
                - backup
                - "/backup"
              volumeMounts:
                - mountPath: /backup
                  name: backup-folder
                  readOnly: true
                - mountPath: /etc/rustic
                  name: config
                {{- if .Values.persistence }}
                - name: cache
                  mountPath: /cache
                {{- end }}
              resources:
                {{- toYaml .Values.rustic.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.rustic.securityContext | nindent 16 }}
          volumes:
            - name: backup-folder
              {{- toYaml .Values.rustic.backup_volume | nindent 14 }}
            {{- with .Values.persistence }}
            - name: cache
              {{- toYaml . | nindent 14 }}
            {{- end }}
            - name: config
              secret:
                secretName: {{ include "rustic.fullname" . }}-config
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
