apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "rustic.fullname" . }}
  labels:
    {{- include "rustic.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "rustic.labels" . | nindent 12 }}
        spec:
          automountServiceAccountToken: false
          hostname: {{ .Values.hostname }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          initContainers:
            - name: rclone
              image: "{{ .Values.rclone.image.repository }}:{{ .Values.rclone.image.tag }}"
              imagePullPolicy: {{ .Values.rclone.image.pullPolicy }}
              restartPolicy: Always
              args:
                - serve
                - restic
                - -v
                - --addr
                - :8080
                - repo:{{ .Values.s3.repo.bucket }}
              volumeMounts:
                - mountPath: /config/rclone
                  name: rclone-config
              startupProbe:
                httpGet:
                  path: /
                  port: 8080
                  httpHeaders:
                    - name: Accept
                      value: application/vnd.x.restic.rest.v2
                failureThreshold: 30
                periodSeconds: 1
              resources:
                {{- toYaml .Values.rclone.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.rclone.securityContext | nindent 16 }}
            {{- if .Values.s3.repo_hot }}
            - name: rclone-hot
              image: "{{ .Values.rclone.image.repository }}:{{ .Values.rclone.image.tag }}"
              imagePullPolicy: {{ .Values.rclone.image.pullPolicy }}
              restartPolicy: Always 
              args:
                - serve
                - restic
                - -v
                - --addr
                - :8081
                - repo-hot:{{ .Values.s3.repo_hot.bucket }}
              volumeMounts:
                - mountPath: /config/rclone
                  name: rclone-hot-config
              startupProbe:
                httpGet:
                  path: /
                  port: 8081
                  httpHeaders:
                    - name: Accept
                      value: application/vnd.x.restic.rest.v2
                failureThreshold: 30
                periodSeconds: 1
              resources:
                {{- toYaml .Values.rclone.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.rclone.securityContext | nindent 16 }}
            {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.rustic.image.repository }}:{{ .Values.rustic.image.tag  | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.rustic.image.pullPolicy }}
              args:
                - backup
                - --password-file
                - "/etc/rustic/.rustic"
                - --repository
                - rest:http://localhost:8080/
                {{- if .Values.s3.repo_hot }}
                - --repo-hot
                - rest:http://localhost:8081/
                {{- end }}
                {{- if .Values.persistence }}
                - --cache-dir
                - /cache
                {{- end }}
                - "/backup"
              volumeMounts:
                - mountPath: /backup
                  name: backup-folder
                  readOnly: true
                - mountPath: /etc/rustic
                  name: rustic-encryption-secret
                {{- if .Values.persistence }}
                - name: cache
                  mountPath: /cache
                {{- end }}
              resources:
                {{- toYaml .Values.rustic.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.rustic.securityContext | nindent 16 }}
          volumes:
            - name: backup-folder
              {{- toYaml .Values.rustic.backup_volume | nindent 14 }}
            - name: rustic-encryption-secret
              secret:
                secretName: {{ include "rustic.fullname" . }}-encryption-secret
            {{- with .Values.persistence }}
            - name: cache
              {{- toYaml . | nindent 14 }}
            {{- end }}
            - name: rclone-config
              secret:
                secretName: {{ include "rustic.fullname" . }}-rclone
            {{- if .Values.s3.repo_hot }}
            - name: rclone-hot-config
              secret:
                secretName: {{ include "rustic.fullname" . }}-rclone-hot
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
