{{- if eq .Values.rustic.init true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rustic.fullname" . }}-init
  labels:
    {{- include "rustic.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        {{- include "rustic.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.rustic.image.repository }}:{{ .Values.rustic.image.tag  | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rustic.image.pullPolicy }}
          args:
            - init
          volumeMounts:
            - mountPath: /etc/rustic
              name: config
          resources:
            {{- toYaml .Values.rustic.resources | nindent 16 }}
          securityContext:
            {{- toYaml .Values.rustic.securityContext | nindent 16 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "rustic.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
{{- end }}