apiVersion: v1
kind: Secret
metadata:
    name: {{ include "rustic.fullname" . }}-encryption-secret
type: Opaque
stringData:
    .rustic: "{{ .Values.rustic.encryption_secret }}"

---
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "rustic.fullname" . }}-rclone
type: Opaque
stringData:
    rclone.conf: |
        [repo]
        type = s3
        provider = 
        env_auth = false
        endpoint = {{ .Values.s3.repo.endpoint }}
        access_key_id = {{ .Values.s3.repo.access_key_id }}
        secret_access_key = {{ .Values.s3.repo.secret_access_key }}
        region = {{ .Values.s3.repo.region }}
        location_constraint =
        acl = private
        server_side_encryption =
        storage_class = {{ .Values.s3.repo.storage_class }}

{{- if .Values.s3.repo_hot }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "rustic.fullname" . }}-rclone-hot
type: Opaque
stringData:
    rclone.conf: |
        [repo-hot]
        type = s3
        provider = 
        env_auth = false
        endpoint = {{ .Values.s3.repo_hot.endpoint }}
        access_key_id = {{ .Values.s3.repo_hot.access_key_id }}
        secret_access_key = {{ .Values.s3.repo_hot.secret_access_key }}
        region = {{ .Values.s3.repo_hot.region }}
        location_constraint =
        acl = private
        server_side_encryption =
        storage_class = {{ .Values.s3.repo_hot.storage_class }}

{{- end }}