apiVersion: v1
kind: Secret
metadata:
    name: {{ include "rustic.fullname" . }}-config
type: Opaque
stringData:
    rustic.toml: |
        [repository]
        repository = "opendal:s3"
{{- if .Values.s3.repo_hot }}
        repo-hot = "opendal:s3"
{{- end }}
        password = "{{ .Values.rustic.encryption_secret }}"
{{- if .Values.persistence }}
        cache-dir = "/cache"
{{- end }}

{{- if .Values.s3.repo_hot }}
        [repository.options-cold]
{{- else}}
        [repository.options]
{{- end }}
        endpoint = "https://{{ .Values.s3.repo.endpoint }}"
        bucket = "{{ .Values.s3.repo.bucket }}"
        region = "{{ .Values.s3.repo.region }}"
        access_key_id = "{{ .Values.s3.repo.access_key_id }}"
        secret_access_key = "{{ .Values.s3.repo.secret_access_key }}"
        default_storage_class = "{{ .Values.s3.repo.storage_class }}"

{{- if .Values.s3.repo_hot }}
        [repository.options-hot]
        endpoint = "https://{{ .Values.s3.repo_hot.endpoint }}"
        bucket = "{{ .Values.s3.repo_hot.bucket }}"
        region = "{{ .Values.s3.repo_hot.region }}"
        access_key_id = "{{ .Values.s3.repo_hot.access_key_id }}"
        secret_access_key = "{{ .Values.s3.repo_hot.secret_access_key }}"
        default_storage_class = "{{ .Values.s3.repo_hot.storage_class }}"
{{- end }}
